# Generated by Django 3.1.7 on 2021-03-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=300)),
                ('BRANCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.branch')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.login')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_material_name', models.CharField(max_length=50)),
                ('gsm', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='request_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('MANAGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.manager')),
            ],
        ),
        migrations.CreateModel(
            name='sales_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('discount', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.login')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('BRANCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.branch')),
                ('RAW_MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.raw_material')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('profile_img', models.CharField(max_length=300)),
                ('BRANCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.branch')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.login')),
            ],
        ),
        migrations.CreateModel(
            name='sales_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.product')),
                ('SALES_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.sales_master')),
            ],
        ),
        migrations.AddField(
            model_name='sales_master',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.user'),
        ),
        migrations.CreateModel(
            name='request_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('RAW_MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.raw_material')),
                ('REQUEST_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.request_master')),
            ],
        ),
        migrations.CreateModel(
            name='request_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.user')),
            ],
        ),
        migrations.CreateModel(
            name='raw_material_used',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('quantity_used', models.CharField(max_length=50)),
                ('RAW_MATERIAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.raw_material')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.staff')),
            ],
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('stock', models.CharField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.product')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('BRANCH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.branch')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.product')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.user')),
            ],
        ),
        migrations.CreateModel(
            name='allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.CharField(max_length=50)),
                ('narration', models.CharField(max_length=50)),
                ('REQUEST_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SCM_System.request_master')),
            ],
        ),
    ]
